services:
  - type: web
    name: actual-sync
    env: node
    plan: free
    buildCommand: npm install -g @actual-app/sync-server
    startCommand: bash -c "echo '{\"port\":' $PORT '}' > config.json && actual-server --config config.json"
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
